-- This is going to provide a list of the templates with details on the fields and certain settings such as Password Changer and Password Character Sets

SELECT [template].[SecretTypeName] AS [Template Name]
, [template].[Active] AS [Template Active]
, [template].[ValidatePasswordRequirementsOnCreate]
, [template].[ValidatePasswordRequirementsOnEdit]
, [template].[DefaultPrivilegedAccountSecretId]
, [passwordTypes].Name AS [Password Type]
, [passwordTypes].[Active] AS [Password Type Active]
, [fields].[SecretFieldName]
, [fields].[FieldSlugName]
, [fields].[SortOrder]
, [fields].[Required]
, [fields].[MustEncrypt]
, [fields].[IsPassword]
, [fields].[IsFile]
, [fields].[IsUrl]
, [fields].[IsNotes]
, [fields].[IsIndexable]
, [fields].[HistoryLength]
, [fields].[Active] [Field Active]
, [fields].[EditablePermission]
, [fields].[HideOnView]
, [fields].[GeneratePasswordCharacterSet]
, [fields].[GeneratePasswordLength]
FROM tbSecretType as [template]
INNER JOIN tbSecretField AS [fields] ON [fields].[SecretTypeId] = [template].[SecretTypeId]
INNER JOIN tbPasswordType AS [passwordTypes] ON [passwordTypes].[PasswordTypeId] = [template].[PasswordTypeId]
WHERE [template].[Active] = 1
